name: Deploy Database

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init and Apply
        env:
          TF_VAR_postgres_user:               ${{ secrets.DB_USER }}
          TF_VAR_postgres_password:           ${{ secrets.DB_PASSWORD }}
          TF_VAR_postgres_db:                 ${{ vars.DB_NAME }}
          TF_VAR_kind_endpoint:               ${{ secrets.KIND_ENDPOINT }}
          TF_VAR_kind_client_certificate:     ${{ secrets.KIND_CLIENT_CERTIFICATE }}
          TF_VAR_kind_client_key:             ${{ secrets.KIND_CLIENT_KEY }}
          TF_VAR_kind_cluster_ca_certificate: ${{ secrets.KIND_CLUSTER_CA_CERTIFICATE }}
        run: terraform -chdir=infra init && terraform -chdir=infra apply -auto-approve
